version: '3'
services: 
  # app.backend:
  #   container_name: app-backend
  #   build: .
  #   ports:
  #    - 7070:7070
  #   environment:
  #     - TZ=UTC
  #     - NODE_ENV
  #     - AWS_ACCESS_KEY_ID
  #     - AWS_SECRET_ACCESS_KEY
  #     - AWS_DEFAULT_REGION
  #   depends_on:
  #    - postgres

  postgres:
    container_name: nestjs_postgrel
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: nestjs
    volumes:
      - postgres:/var/lib/postgresql/data
    networks: 
      - postgres-host

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres-host
    restart: unless-stopped
networks:
  postgres-host:
    driver: bridge
volumes:
  postgres:
  pgadmin:

  